export const SET_CURRENT_PATH = 'SET_CURRENT_PATH';
export const SET_PREVIOUS_PATH = 'SET_PREVIOUS_PATH';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const CURRENT_PAGE_TITLE = 'CURRENT_PAGE_TITLE';
export const CAN_SCREEN_GO_BACK = 'CAN_SCREEN_GO_BACK';